### PR TITLE
Issue 7 rename table in schema

### PR DESCRIPTION
**Pull request by baburdick**
Initial, non-working attempt to make rename_table schema-aware in response to HornsAndHooves/pg_saurus#7

### CODE REVIEW

**Comment by baburdick** [comment]
It appears that `alias_method_chain` is not working for `rename_table`.
```
Failures:

  1) PgSaurus::ConnectionAdapters::AbstractAdapter::SchemaMethods#rename_table_with_schema_option renames table with schema option
     Failure/Error: connection.rename_table("something", "something_else", schema: "demography")
     ArgumentError:
       wrong number of arguments (3 for 2)
     # /Users/bruceb/.rvm/gems/ruby-2.1.5@pg_saurus/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:379:in `rename_table'
     # ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:52:in `block (3 levels) in <top (required)>'

  2) PgSaurus::ConnectionAdapters::AbstractAdapter::SchemaMethods#rename_table_with_schema_option allows options to be a frozen Hash
     Failure/Error: expect { connection.rename_table("something", "something_else", options) }.not_to raise_error
       expected no Exception, got #<ArgumentError: wrong number of arguments (3 for 2)> with backtrace:
         # /Users/bruceb/.rvm/gems/ruby-2.1.5@pg_saurus/gems/activerecord-4.1.12/lib/active_record/connection_adapters/postgresql/schema_statements.rb:379:in `rename_table'
         # ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:63:in `block (4 levels) in <top (required)>'
         # ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:63:in `block (3 levels) in <top (required)>'
     # ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:63:in `block (3 levels) in <top (required)>'

Finished in 0.62685 seconds (files took 1.42 seconds to load)
186 examples, 2 failures, 2 pending

Failed examples:

rspec ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:45 # PgSaurus::ConnectionAdapters::AbstractAdapter::SchemaMethods#rename_table_with_schema_option renames table with schema option
rspec ./spec/lib/pg_saurus/connection_adapters/abstract_adapter/schema_methods_spec.rb:60 # PgSaurus::ConnectionAdapters::AbstractAdapter::SchemaMethods#rename_table_with_schema_option allows options to be a frozen Hash
```

**Comment by baburdick** [comment]
Thanks for the fix @albertosaurus!

**Comment by albertosaurus** [comment]
Should take care of everything.

**Comment by albertosaurus** [comment]
@baburdick I've put in a safer way to get the current schema search_path.

**Comment by baburdick** [comment]
Looks good to me.

**Pull request merged**
